window.PRODUCTS = [
  {
    id: "ceramic-coffee-mug",
    name: "Ceramic Coffee Mug",
    category: "Pottery",
    price: 750,
    oldPrice: null,
    image: "assets/images/products/ceramic-coffee-mug.webp",
    shortDescription: "A warm, hand-thrown mug for everyday pauses.",
    description: "Wheel-thrown by hand and finished with a soft olive-brown glaze. Natural variations in tone and texture make every mug quietly unique.",
    material: "Food-safe glazed stoneware",
    dimensions: "350 ml · 9 cm high",
    care: "Hand wash recommended. Microwave safe.",
    stock: 12,
    featured: true,
    newArrival: true,
    bestseller: true,
    badge: "Bestseller"
  },
  {
    id: "terracotta-vase",
    name: "Handcrafted Terracotta Vase",
    category: "Décor",
    price: 2100,
    oldPrice: 2450,
    image: "assets/images/products/terracotta-vase.webp",
    shortDescription: "An earthy statement vase shaped by artisan hands.",
    description: "Built slowly from natural terracotta and left with an honest matte finish. A sculptural piece for dried stems, shelves and calm corners.",
    material: "Natural terracotta clay",
    dimensions: "31 × 18 cm",
    care: "Use with dried stems. Wipe with a soft dry cloth.",
    stock: 5,
    featured: true,
    newArrival: false,
    bestseller: false,
    badge: "Limited"
  },
  {
    id: "glazed-serving-bowl",
    name: "Glazed Serving Bowl",
    category: "Pottery",
    price: 1450,
    oldPrice: null,
    image: "assets/images/products/serving-bowl.webp",
    shortDescription: "A generous handmade bowl in sand and olive tones.",
    description: "A versatile serving bowl with a tactile matte exterior and quietly glazed interior. Made for shared meals and everyday tables.",
    material: "Food-safe glazed stoneware",
    dimensions: "24 cm diameter",
    care: "Hand wash recommended. Do not place on direct flame.",
    stock: 8,
    featured: true,
    newArrival: true,
    bestseller: false,
    badge: "New"
  },
  {
    id: "handwoven-jute-basket",
    name: "Handwoven Jute Basket",
    category: "Baskets",
    price: 1299,
    oldPrice: 1499,
    image: "assets/images/products/jute-basket.webp",
    shortDescription: "Natural storage that brings texture to a room.",
    description: "Handwoven from sturdy natural jute with comfortable loop handles. Use it for throws, toys, laundry or planters.",
    material: "100% natural jute",
    dimensions: "30 × 30 × 35 cm",
    care: "Wipe clean. Keep away from prolonged moisture.",
    stock: 9,
    featured: true,
    newArrival: false,
    bestseller: true,
    badge: "Bestseller"
  },
  {
    id: "round-storage-basket",
    name: "Round Storage Basket",
    category: "Baskets",
    price: 899,
    oldPrice: null,
    image: "assets/images/products/round-basket.webp",
    shortDescription: "A lidded basket for little everyday essentials.",
    description: "Tightly handwoven in a soft round form with a fitted lid. Beautiful on a bedside table, desk or bathroom shelf.",
    material: "Natural jute and cotton thread",
    dimensions: "22 × 12 cm",
    care: "Dust with a soft brush or wipe with a dry cloth.",
    stock: 14,
    featured: false,
    newArrival: true,
    bestseller: false,
    badge: "New"
  },
  {
    id: "jute-planter-basket",
    name: "Jute Planter Basket",
    category: "Baskets",
    price: 699,
    oldPrice: null,
    image: "assets/images/products/jute-planter.webp",
    shortDescription: "A woven sleeve that softens indoor greenery.",
    description: "A flexible jute planter cover that adds warm natural texture around standard nursery pots.",
    material: "Natural jute",
    dimensions: "Fits pots up to 20 cm",
    care: "Use with a waterproof inner pot. Keep dry.",
    stock: 17,
    featured: true,
    newArrival: false,
    bestseller: false,
    badge: ""
  },
  {
    id: "organic-cotton-tote",
    name: "Organic Cotton Tote Bag",
    category: "Textiles",
    price: 999,
    oldPrice: null,
    image: "assets/images/products/cotton-tote.webp",
    shortDescription: "A roomy everyday tote in unbleached cotton.",
    description: "Minimal, durable and easy to carry. The sturdy handles and generous size make it useful for markets, work and slow weekends.",
    material: "Heavyweight organic cotton canvas",
    dimensions: "40 × 36 cm",
    care: "Cold gentle wash. Air dry in shade.",
    stock: 11,
    featured: true,
    newArrival: false,
    bestseller: true,
    badge: "Bestseller"
  },
  {
    id: "handloom-cushion-cover",
    name: "Handloom Cushion Cover",
    category: "Textiles",
    price: 649,
    oldPrice: 799,
    image: "assets/images/products/cushion-cover.webp",
    shortDescription: "Handwoven cotton with quiet terracotta details.",
    description: "A textured handloom cover finished with subtle woven stripes and corner tassels. An easy layer for sofas and reading chairs.",
    material: "Handwoven cotton",
    dimensions: "45 × 45 cm",
    care: "Gentle hand wash separately. Cushion insert not included.",
    stock: 6,
    featured: true,
    newArrival: true,
    bestseller: false,
    badge: "New"
  },
  {
    id: "natural-table-runner",
    name: "Natural Table Runner",
    category: "Textiles",
    price: 1199,
    oldPrice: null,
    image: "assets/images/products/table-runner.webp",
    shortDescription: "A softly woven runner for unhurried tables.",
    description: "Handwoven in natural cotton with fine terracotta lines and a relaxed tasselled edge. Designed for everyday tables and intimate gatherings.",
    material: "Handwoven cotton",
    dimensions: "180 × 35 cm",
    care: "Cold hand wash. Dry flat in shade.",
    stock: 7,
    featured: false,
    newArrival: true,
    bestseller: false,
    badge: "New"
  }
];
