window.STORE_CONFIG = {
  name: "Mitti & More",
  shortName: "Mitti",
  tagline: "Handmade for slower, warmer living.",
  description: "Thoughtfully curated pottery, baskets and textiles made with natural materials.",
  whatsapp: "919918996096",
  phoneDisplay: "+91 99189 96096",
  email: "hello@mittiandmore.example",
  address: "Gorakhpur, Uttar Pradesh",
  hours: "Mon–Sat · 10:00 AM–7:00 PM",
  currency: "INR",
  freeShippingAbove: 1999,
  deliveryNote: "Delivery charges and final availability will be confirmed on WhatsApp.",
  instagram: "#",
  facebook: "#",
  mapsUrl: "#",
  announcement: "Free shipping above ₹1,999 · WhatsApp orders",
  demoMode: false,
  apiBase: "https://script.google.com/macros/s/AKfycbzrmHUPMbNnvYO5sNmJO5_BI3Nr_WfkVMUajoLmMvC9P77jl1FBhiaw4qu1KEj8OeDMtQ/exec",
  defaultAd: {
    ad_id: "AD001",
    active: "Yes",
    badge: "Limited Slots",
    headline: "WhatsApp pe Catalog + Order",
    subheadline: "Google Sheet pe track. Chhoti dukaan ke liye simple setup.",
    offer_price: "1999",
    compare_price: "3999",
    cta_text: "Message Karein",
    image_url: "assets/images/hero/hero-home.jpg",
    wa_number: "919918996096",
    wa_prefill: "Namaste, demo bhejiye",
    theme: "#166534"
  }
};
